Parameters:
  KomaInstanceType:
    Description: Select EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
    ConstraintDescription: Your ec2 cost.

Resources:
  KomaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        { "Fn::Select": ["0", { "Fn::GetAZs": { "Ref": "AWS::Region" } }] }
      ImageId: ami-0404778e217f54308
      InstanceType: !Ref KomaInstanceType