Resources:
  ec2ForCloudformation:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        { "Fn::Select": ["0", { "Fn::GetAZs": { "Ref": "AWS::Region" } }] }
      # AMI-ID
      ImageId: ami-0720a3ca2735bf2fa
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHWEBSG

  mywebEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref ec2ForCloudformation

  SSHWEBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and Web PORT
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0