Parameters:
  #https://deeplearnaws-cf-tpl-20250126.s3.eu-west-1.amazonaws.com/lesson25sg.yml
  TemplateURL:
    Description: URL of the nested stack template
    Type: String

Resources:
  WebSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateURL
      Parameters:
        AppName: !Ref AWS::StackName
      TimeoutInMinutes: 10

  WebEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0720a3ca2735bf2fa
      SecurityGroupIds:
        - !GetAtt WebSecurityGroupStack.Outputs.WebGroupId